language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable
  firefox: latest

cache:
  yarn: true

env:
  global:
    - JOBS=1
    - COVERAGE=true
    - BROWSERSTACK_USERNAME=caluma1
    - secure: MVUSNHfxhStXejmWm66ZZaA81FX+EG37UPpC0g+E+acsIwTVxZ8lRNfQyMKt8nQwsnTN+NGikj5puuHhVZUSKzULzAGk4iUiQ7t0YQrdNl6rJIsOBbVqQ43NcwF+yuuyJkSOiAaEqhag7mtbTg2jgjPf8v78b5aba8uK/AXg0sA4rObkm564TSyBp5ujfTT6w6BA1R2MiZNFTDAUefpTh6Fl9/brsBs0ga9ZfHxBUXmtln+RFSmUaze4A2Q/vows7bzFgMD74dMc4FsApJjrOrscBwsIEKvtxbWXcDQuam1GFWXBVaMtnOucT+1eaXogbDg9NlvlPnJ875jyC7ty+yJfmVcxwVVGETP7Y5XQzmH7As1R4bOp9eQyb7yjeuS/3YzF9GSO7SLxEovENzs7c6sHq9d7vAh1Uz7jDzoZaN6kroGl7Czpl5G/RLUaoQOvjvYZz/jiiEhbIj/k3c0b0pWvm4A/z6E5nE0P7I255YTcqQhNWSwc+xVsWY8qtSJiEqTq3xdqfWiSSALwTz0ivUY99AgXYrvxfAhNOW/rEPK346T+5FE8jDQ+R16Ha95i6h6HEkcuJei00uEHmULaLhNg1mh4mZr88aGrI3BsK0th7rqs0NVVOHGYjnOG+qTlrGBTNO8vvWFhh3kRgeelDaR4XIr2Z50d+IcwS9hzGS0=


branches:
  only:
    - master
    - release
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-release

  include:
    # runs linting and tests with current locked deps

    - stage: Tests
      name: Tests
      install:
        - yarn install --non-interactive
      script:
        - commitlint-travis
        - yarn lint:hbs
        - yarn lint:js
        - yarn test

    - name: Browserstack Tests
      install:
        - yarn install --non-interactive
      script:
        - yarn ember browserstack:connect
        - yarn test:browserstack
        - yarn ember browserstack:results
        - yarn ember browserstack:disconnect

    - name: Floating Dependencies
      script:
        - yarn test

    - stage: Additional Tests
      env: EMBER_TRY_SCENARIO=ember-lts-3.12
    - env: EMBER_TRY_SCENARIO=ember-release

    - stage: Release
      name: Release
      if: branch = release and type = push
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        on:
          branch: release
        script:
          - yarn semantic-release

    - stage: Deploy
      name: Deploy
      if: "(branch = master or tag is present) and type = push"
      script: yarn ember deploy production

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn ember try:one $EMBER_TRY_SCENARIO

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
