language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - COVERAGE=true

branches:
  only:
    - master
    - release
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-release

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:hbs
        - yarn lint:js
        - yarn test

    - name: "Floating Dependencies"
      script:
        - yarn test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-3.8
    - env: EMBER_TRY_SCENARIO=ember-release

    - stage: "Release"
      if: branch = release and type = push
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        on:
          branch: release
        script:
          - yarn semantic-release

    - stage: "Deploy"
      if: (branch = master or tag is present) and type = push
      script: yarn ember deploy production

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn ember try:one $EMBER_TRY_SCENARIO

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
