export default {
  Node: [
    "Workflow",
    "Form",
    "Document",
    "Case",
    "WorkItem",
    "Flow",
    "DynamicOption",
    "Option",
    "TextQuestion",
    "StringAnswer",
    "ChoiceQuestion",
    "MultipleChoiceQuestion",
    "ListAnswer",
    "DynamicChoiceQuestion",
    "DynamicMultipleChoiceQuestion",
    "TextareaQuestion",
    "FloatQuestion",
    "FloatAnswer",
    "IntegerQuestion",
    "IntegerAnswer",
    "DateQuestion",
    "DateAnswer",
    "TableQuestion",
    "TableAnswer",
    "FormQuestion",
    "FileQuestion",
    "StaticQuestion",
    "FileAnswer",
    "File",
    "CalculatedFloatQuestion",
    "ActionButtonQuestion",
    "SimpleTask",
    "CompleteWorkflowFormTask",
    "CompleteTaskFormTask",
  ],
  Task: ["SimpleTask", "CompleteWorkflowFormTask", "CompleteTaskFormTask"],
  Question: [
    "TextQuestion",
    "ChoiceQuestion",
    "MultipleChoiceQuestion",
    "DynamicChoiceQuestion",
    "DynamicMultipleChoiceQuestion",
    "TextareaQuestion",
    "FloatQuestion",
    "IntegerQuestion",
    "DateQuestion",
    "TableQuestion",
    "FormQuestion",
    "FileQuestion",
    "StaticQuestion",
    "CalculatedFloatQuestion",
    "ActionButtonQuestion",
  ],
  Answer: [
    "StringAnswer",
    "ListAnswer",
    "FloatAnswer",
    "IntegerAnswer",
    "DateAnswer",
    "TableAnswer",
    "FileAnswer",
  ],
  DynamicQuestion: ["DynamicChoiceQuestion", "DynamicMultipleChoiceQuestion"],
};
