version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    default_reviewers:
      - "anehx"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
      - match:
          dependency_type: "production"
          update_type: "in_range"
    ignored_updates:
      # ember-changeset and ember-changeset-validations v3+ require Proxy
      # objects which do not work in IE11
      - match:
          dependency_name: "ember-changeset"
          version_requirement: ">= 3"
      - match:
          dependency_name: "ember-changeset-validations"
          version_requirement: ">= 3"

      # graphql-tools v5+ breaks generic mocking
      - match:
          dependency_name: "graphql-tools"
          version_requirement: ">= 5"

      # https://github.com/jasonmit/ember-cli-moment-shim/issues/183
      - match:
          dependency_name: "ember-cli-moment-shim"
          version_requirement: "> 3.8.0"
      - match:
          dependency_name: "moment"
          version_requirement: "> 2.24.0"
