name: Release

on:
  workflow_dispatch:

env:
  NODE_VERSION: 20

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: pnpm/action-setup@v4
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Configure pnpm
        run: |
          pnpm config set registry https://registry.npmjs.org
          pnpm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Prepare release
        run: pnpm semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Publish packages
        if: github.ref == 'refs/heads/main'
        run: pnpm publish -r
      - name: Publish packages (beta)
        if: github.ref == 'refs/heads/beta'
        run: pnpm publish -r --tag beta --publish-branch beta
